run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - godot
    - lll

linters-settings:
  godot:
    scope: all
    capital: false
    period: true
  lll:
    line-length: 120
    tab-width: 4
